### ISSUE TITLE
Extend Audioplayer and add settings

### ISSUE THREAD

**Issue by thervh70** [thervh70/SEM_Team9#124]
Add enumeration for different types of audio. Now we will be able to distinguish different types of audio (e.g. soundtrack, sound effects).
In that case we can generate different sound settings, for example only enabling the sound effects and disabling the soundtrack.

**Comment by thervh70** [comment]
Please remember that the audioplayer has to be extended even further. Please take a look at #35

**Comment by mdingjan** [comment]
Everything works now. I didn't add an enumeration, but found a more effective solution and added this by refactoring.
There is now an Abstract class AudioPlayer which has two childs; SoundtrackPlayer and SoundEffectsPlayer. This is because a soundtrack must be handled differently than a sound effect. Soundtracks must be able to be modified on the fly. Sound effects are just played.

I added a lot more, you can have a look at this during the review.
I'm going to create a PR for this.

<feature,review
