### ISSUE TITLE
High score list backend

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#29]
There needs to be a high score list that keeps track of the highest scores that players have reached

**Comment by mpsijm** [comment]
Now waiting until #140 has finished its refactoring. Once there is a Scene in which you can login with your GameJolt token, the highscores can be sent to the cloud.

**Comment by mpsijm** [comment]
Due to the assignment given by Jurgen, here are the requirements,
- The game shall feature a highscore functionality.
  - Every time the player dies, the score gets sent to an external server.
  - The user shall be able to view its ten best scores ever achieved.
  - The user shall be able to view the ten global highscores.
    - The global highscore list shall only contain the best entry per user.
